const facts = [
  "Smoking leads to disease and disability and harms nearly every organ of the body.",
  "Quitting smoking lowers your risk for smoking-related diseases and can add years to your life.",
  "Smoking causes more deaths each year than the following causes combined: human immunodeficiency virus (HIV), illegal drug use, alcohol use, motor vehicle injuries, firearm-related incidents.",
  "Smoking causes about 90% (or 9 out of 10) of all lung cancer deaths. More women die from lung cancer each year than from breast cancer.",
  "Smoking causes about 80% (or 8 out of 10) of all deaths from chronic obstructive pulmonary disease (COPD).",
  "Cigarette smoking increases risk for death from all causes in men and women.",
  "Smokers are more likely than nonsmokers to develop heart disease, stroke, and lung cancer.",
  "Estimates show smoking increases the risk: for coronary heart disease by 2 to 4 times.",
  "Estimates show smoking increases the risk: for stroke by 2 to 4 times.",
  "Estimates show smoking increases the risk: of men developing lung cancer by 25 times.",
  "Estimates show smoking increases the risk: of women developing lung cancer by 25.7 times.",
  "Smoking causes diminished overall health, increased absenteeism from work, and increased health care utilization and cost.",
  "Smokers are at greater risk for diseases that affect the heart and blood vessels (cardiovascular disease).",
  "Even people who smoke fewer than five cigarettes a day can have early signs of cardiovascular disease.",
  "Smoking damages blood vessels and can make them thicken and grow narrower. This makes your heart beat faster and your blood pressure go up. Clots can also form.",
  "Blockages caused by smoking can also reduce blood flow to your legs and skin.",
  "Smoking can cause lung disease by damaging your airways and the small air sacs (alveoli) found in your lungs.",
  "Lung diseases caused by smoking include COPD, which includes emphysema and chronic bronchitis.",
  "Cigarette smoking causes most cases of lung cancer.",
  "If you have asthma, tobacco smoke can trigger an attack or make an attack worse.",
  "Smokers are 12 to 13 times more likely to die from COPD than nonsmokers.",
  "Smoking can cause cancer almost anywhere in your body: bladder, blood (acute myeloid leukemia), cervix, colon and rectum (colorectal), esophagus, kidney and ureter, larynx, liver, oropharynx (includes parts of the throat, tongue, soft palate, and the tonsils), pancreas, stomach, trachea, bronchus, and lung.",
  "Smoking also increases the risk of dying from cancer and other diseases in cancer patients and survivors.",
  "Smoking can make it harder for a woman to become pregnant. It can also affect her baby’s health before and after birth. Smoking increases risks for: preterm (early) delivery, stillbirth (death of the baby before birth), low birth weight, sudden infant death syndrome (known as SIDS or crib death), ectopic pregnancy, orofacial clefts in infants.",
  "Smoking can also affect men’s sperm, which can reduce fertility and also increase risks for birth defects and miscarriage.",
  "Smoking can affect bone health. Women past childbearing years who smoke have weaker bones than women who never smoked. They are also at greater risk for broken bones.",
  "Smoking affects the health of your teeth and gums and can cause tooth loss.",
  "Smoking can increase your risk for cataracts (clouding of the eye’s lens that makes it hard for you to see). It can also cause age-related macular degeneration (AMD). AMD is damage to a small spot near the center of the retina, the part of the eye needed for central vision.",
  "Smoking is a cause of type 2 diabetes mellitus and can make it harder to control. The risk of developing diabetes is 30–40% higher for active smokers than nonsmokers.",
  "Smoking causes general adverse effects on the body, including inflammation and decreased immune function.",
  "Smoking is a cause of rheumatoid arthritis.",
];

export default facts;
